"use client";
// import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "styled-components";
import { useState } from "react";
import { darkTheme, lightTheme } from "./utils/Themes";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import styled from "styled-components";
// import { metadata } from "./metadata";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const Body = styled.div`
  background-color: ${({ theme }) => theme.bg};
  width: 100%;
  overflow-x: hidden;
`;

// export const metadata = {
//   title: "My Custom Title",
//   description: "This is my website description",
//   icons: "/favicon.ico", // Path to your favicon
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [darkMode, setDarkMode] = useState(true);

  const handleToggleDarkMode = () => {
    // setDarkMode(!darkMode);
    setDarkMode((prev) => !prev);
  };

  return (
    <html lang="en">
      <head>
        <title>Bhairavi Gawas</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo2.svg" type="image/svg+xml"/>
      </head>
      <body 
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider theme={darkMode ? darkTheme : lightTheme}>
          <Navbar handleToggleDarkMode={handleToggleDarkMode} darkMode={darkMode}/>
          <Body>{children}</Body>
          <Footer />

        </ThemeProvider>
      </body>
    </html>
  );
}
